services:
  - name: milliyet-archive-api
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: data
      mountPath: /data
      sizeGB: 1